<div style="
    background: linear-gradient(135deg, #667eea, #764ba2);
    padding: 40px;
    border-radius: 20px;
    color: white;
    font-family: 'Segoe UI', sans-serif;
    box-shadow: 0px 10px 30px rgba(0,0,0,0.3);
    text-align: center;
">
 
  <div class="heading-wrapper">
    <div class="heading-inner"> 
      <h1 style="
          margin: 0;
          font-size: 36px;
          letter-spacing: 1px;
          text-shadow: 0px 4px 15px rgba(0,0,0,0.4);
      ">
        HOSPITAL EMERGENCY ROOM PERFORMANCE AND PREDICTION PROJECT
      </h1>
    </div>
  </div>

</div>

<div style="
    background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);
    padding: 50px;
    border-radius: 25px;
    color: white;
    font-family: 'Segoe UI', sans-serif;
    box-shadow: 0px 15px 40px rgba(0,0,0,0.4);
    text-align: center;
    backdrop-filter: blur(10px);
    transition: transform 0.4s ease, box-shadow 0.4s ease;
"
onmouseover="this.style.transform='scale(1.03)'; this.style.boxShadow='0px 20px 50px rgba(0,0,0,0.6)'"
onmouseout="this.style.transform='scale(1)'; this.style.boxShadow='0px 15px 40px rgba(0,0,0,0.4)'"
>

  <div class="heading-wrapper">
    <div class="heading-inner"> 
      <h1 style="
          margin: 0;
          font-size: 40px;
          font-weight: 700;
          letter-spacing: 1.5px;
          text-transform: uppercase;
          background: linear-gradient(90deg, #00f5a0, #00d9f5);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          text-shadow: 0px 4px 20px rgba(0,0,0,0.5);
      ">
        HR Analytics: Employee Attrition Prediction System
      </h1>
    </div>
  </div>

</div>

<div style="max-width:800px; margin:20px auto; padding:20px; 
background:#2a5298; color:white; border-radius:15px; 
font-family:Arial; text-align:center;">

<h2 style="margin-bottom:10px;">
Author: Noman Khan
</h2>

<p>
<a href="https://www.linkedin.com/in/noman-khan-100780393/?originalSubdomain=pk">
<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg" width="30">
</a>

<a href="https://github.com/nomankhan0347893-web/mentorship-program-devsil">
<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" width="30">
</a>
</p>

<p style="font-size:15px;">
Learning Data Science and AI from 
<a href="https://codanics.com/" style="color:#00ffff;"><b>Codanics.com</b></a>
<br><br>
Mentor at 
<a href="https://devsil.com/" style="color:#ffd700;"><b>Devsil</b></a>
</p>

</div>

<div style="
    background: linear-gradient(135deg, #1f4037, #99f2c8);
    padding: 25px;
    border-radius: 15px;
    color: white;
    font-family: 'Segoe UI', sans-serif;
    box-shadow: 0px 8px 20px rgba(0,0,0,0.3);
">

<h1 style="text-align:center; color:#ffeaa7;">📑 TABLE OF CONTENTS</h1>
<hr style="border:1px solid white; margin-bottom:20px;">

<h3 style="color:#ffd32a;">1️⃣ Introduction</h3>
<ul>
<li>1.1 Project Overview</li>
<li>1.2 Problem Statement</li>
<li>1.3 Objectives</li>
<li>1.4 Scope of the Project</li>
<li>1.5 Tools & Technologies Used</li>
</ul>

<h3 style="color:#ffd32a;">2️⃣ Dataset Description</h3>
<ul>
<li>2.1 Dataset Source (Kaggle)</li>
<li>2.2 Dataset Overview</li>
<li>2.3 Feature Description</li>
<li>2.4 Target Variable</li>
</ul>

<h3 style="color:#ffd32a;">3️⃣ Data Cleaning & Preparation</h3>
<ul>
<li>3.1 Importing Libraries</li>
<li>3.2 Loading the Dataset</li>
<li>3.3 Initial Data Inspection</li>
<li>3.4 Handling Missing Values</li>
<li>3.5 Removing Duplicate Records</li>
<li>3.6 Date & Time Conversion</li>
<li>3.7 Creating Time-Based Feature</li>
<li>3.8 Outlier Detection & Treatment</li>
<li>3.9 Final Cleaned Dataset</li>
</ul>

<h3 style="color:#ffd32a;">4️⃣ Exploratory Data Analysis (EDA)</h3>
<ul>
<li>4.1 Total Number of Patients</li>
<li>4.2 Average Waiting Time</li>
<li>4.3 Median Waiting Time</li>
<li>4.4 Variance & Standard Deviation</li>
<li>4.5 Waiting Time Distribution</li>
<li>4.6 Patients by Hour</li>
<li>4.7 Patients by Weekday</li>
<li>4.8 Waiting Time by Age Group</li>
<li>4.9 Waiting Time by Gender</li>
<li>4.10 Waiting Time by Triage Level</li>
<li>4.11 Correlation Heatmap</li>
<li>4.12 Top 15 Visualizations</li>
</ul>

<h3 style="color:#ffd32a;">5️⃣ Statistical Reasoning</h3>
<ul>
<li>5.1 Mean vs Median Comparison</li>
<li>5.2 Skewness of Waiting Time</li>
<li>5.3 Correlation Between Numerical Variables</li>
<li>5.4 Correlation Heatmap Analysis</li>
<li>5.5 Key Statistical Insights</li>
</ul>

<h3 style="color:#ffd32a;">6️⃣ Feature Engineering</h3>
<ul>
<li>6.1 Creating New Features</li>
<li>6.2 Time-Based Features</li>
<li>6.3 Grouped Categories</li>
<li>6.4 Encoding Categorical Variables</li>
<li>6.5 Feature Selection</li>
<li>6.6 Final Modeling Dataset</li>
</ul>

<h3 style="color:#ffd32a;">7️⃣ Machine Learning Modeling</h3>
<ul>
<li>7.1 Define Prediction Problem</li>
<li>7.2 Train-Test Split</li>
<li>7.3 Model 1: Linear Regression</li>
<li>7.4 Model 2: Decision Tree</li>
<li>7.5 Model 3: Random Forest</li>
<li>7.6 Model Comparison</li>
</ul>

<h3 style="color:#ffd32a;">8️⃣ Model Evaluation</h3>
<ul>
<li>MAE</li>
<li>MSE</li>
<li>RMSE</li>
<li>R² Score</li>
<li>8.1 Best Model Selection</li>
</ul>

<h3 style="color:#ffd32a;">9️⃣ Business Recommendations</h3>
<ul>
<li>9.1 When is ER Most Busy?</li>
<li>9.2 Which Patients Wait the Longest?</li>
<li>9.3 Factors Increasing Waiting Time</li>
<li>9.4 Recommendations to Reduce Waiting Time</li>
<li>9.5 Staffing Improvement Suggestions</li>
</ul>

<h3 style="color:#ffd32a;">🔟 Final Submission</h3>
<ul>
<li>10.1 Jupyter Notebook</li>
<li>10.2 Cleaned Dataset</li>
<li>10.3 Trained Model File</li>
<li>10.4 Executive Summary</li>
</ul>

</div>

<h3 style="color:#1e3c72; 
           background-color:#e3f2fd; 
           padding:10px; 
           border-radius:8px;">
   1.Introduction
</h3>



<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    1.1 Project Overview
</h3>

This project is about analyzing the performance of a hospital emergency room (ER). In emergency rooms, many patients arrive every day, and some of them have to wait before getting treatment. Long waiting times can create problems for patients and hospital management.

In this project, we study patient data to understand how the emergency room is working. We also build a machine learning model to predict how long a patient might have to wait. This helps the hospital plan better and improve service quality.

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    1.2 Problem Statement
</h3>

Hospitals often face the problem of long waiting times in emergency rooms. When too many patients arrive at the same time, staff become busy and patients have to wait longer.

The main problem is:

* The hospital does not clearly know when the ER is most busy.

* They cannot predict waiting time in advance.

* Some patients may wait longer than others.

So, we need to analyze the data and build a system that can predict waiting time and help reduce delays.

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    1.3 Objectives
</h3>

The main objectives of this project are:

* To clean and prepare the emergency room dataset

* To analyze patient arrival patterns

* To calculate average and median waiting time

* To find which factors increase waiting time

* To build machine learning models to predict waiting time

* To suggest improvements for hospital management
  
<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    1.4 Scope of the Project
</h3>

This project focuses only on emergency room data. It studies patient arrival time, age, gender, triage level, and waiting time.

The project includes:

* Data cleaning

* Data analysis and visualization

* Statistical reasoning

* Feature engineering

* Machine learning modeling

* Business recommendations

It does not include real-time hospital system implementation. It is based only on the given dataset.

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
     1.5 Tools & Technologies Used
</h3>

The following tools and technologies are used in this project:

Python – for data analysis and modeling

Pandas – for data handling

NumPy – for numerical calculations

Matplotlib & Seaborn – for data visualization

Scikit-learn – for machine learning models

Jupyter Notebook – for coding and documentation

These tools help us clean the data, analyze patterns, build prediction models, and present results clearly.

<h3 style="color:#1e3c72; 
           background-color:#e3f2fd; 
           padding:10px; 
           border-radius:8px;">
   2.Dataset Description
</h3>



<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    2.1 Dataset Source (Kaggle)
</h3>

The dataset used in this project is taken from Kaggle. Kaggle is an online platform where people share datasets for learning and practice.

The dataset is related to emergency room waiting time. It contains patient information such as arrival time, age, gender, triage level, and waiting time.

This dataset helps us understand how the emergency room works and how long patients usually wait before getting treatment.

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    2.2 Dataset Overview
</h3>


The dataset contains records of patients who visited the emergency room. Each row represents one patient visit.

The dataset includes:

* Patient details

* Arrival time information

* Triage level (priority level)

* Waiting time

* The data helps us analyze:

* How many patients come per day

* At what time the ER is most busy

* Which patients wait longer

* What factors affect waiting time

Before using the data, we clean it to remove missing values and duplicates.

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    2.3 Feature Description
</h3>


Below are the main features (columns) in the dataset:


| Column Name                          | Description                                                           |
| ------------------------------------ | --------------------------------------------------------------------- |
| `Visit ID`                           | Unique identifier for each visit.                                     |
| `Patient ID`                         | Unique identifier for each patient.                                   |
| `Hospital ID`                        | Unique identifier for each hospital.                                  |
| `Hospital Name`                      | Name of the hospital.                                                 |
| `Region`                             | Classification as Urban or Rural.                                     |
| `Visit Date`                         | Date and time of the patient’s visit.                                 |
| `Day of Week`                        | Day of the week (e.g., Monday, Tuesday).                              |
| `Season`                             | Season of the visit (Winter, Spring, Summer, Fall).                   |
| `Time of Day`                        | Time slot of the visit (e.g., Early Morning, Afternoon).              |
| `Urgency Level`                      | Urgency classification: Critical, High, Medium, Low.                  |
| `Nurse-to-Patient Ratio`             | Ratio of nurses to patients during the visit.                         |
| `Specialist Availability`            | Number of specialists available at the hospital.                      |
| `Facility Size (Beds)`               | Number of available beds at the facility.                             |
| `Time to Registration (min)`         | Time taken to complete registration.                                  |
| `Time to Triage (min)`               | Time taken for triage assessment.                                     |
| `Time to Medical Professional (min)` | Time taken to see a doctor or healthcare professional.                |
| `Total Wait Time (min)`              | Total time from arrival to seeing a medical professional.             |
| `Patient Outcome`                    | Outcome of the visit (Admitted, Discharged, Left Without Being Seen). |
| `Patient Satisfaction`               | Satisfaction score (1 to 5, with 5 being the highest).                |

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    2.4 Target Variable
</h3>


The target variable in this project is:

**Waiting Time**

This is the value we want to predict using machine learning.\
Waiting time shows how long a patient waited before receiving medical attention. By predicting waiting time, the hospital can:

* Prepare staff in advance

* Reduce long delays

* Improve patient satisfaction

* Manage emergency room operations better

Since waiting time is a number (in minutes), this is a regression problem.

<h3 style="color:#1e3c72; 
           background-color:#e3f2fd; 
           padding:10px; 
           border-radius:8px;">
   3.Data Cleaning & Preparation
</h3>

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    3.1 Importing Libraries
</h3>

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# For preprocessing and modeling
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report,roc_curve,roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

import warnings
warnings.filterwarnings('ignore')

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    3.2 Data Loading
</h3>

In [21]:
df=pd.read_csv('ER Wait Time Dataset.csv')

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    3.3 Initial Data Inspection
</h3>

In [22]:
df.head(
    
)

,Visit ID,Patient ID,Hospital ID,Hospital Name,Region,Visit Date,Day of Week,Season,Time of Day,Urgency Level,Nurse-to-Patient Ratio,Specialist Availability,Facility Size (Beds),Time to Registration (min),Time to Triage (min),Time to Medical Professional (min),Total Wait Time (min),Patient Outcome,Patient Satisfaction
0,HOSP-1-20240210-0001,PAT-00001,HOSP-1,Springfield General Hospital,Urban,2024-02-10 20:20:56,Saturday,Winter,Late Morning,Medium,4,3,92,17,22,66,105,Discharged,1
1,HOSP-3-20241128-0001,PAT-00002,HOSP-3,Northside Community Hospital,Rural,2024-11-28 02:07:47,Thursday,Fall,Evening,Medium,4,0,38,9,30,30,69,Discharged,3
2,HOSP-3-20240930-0002,PAT-00003,HOSP-3,Northside Community Hospital,Rural,2024-09-30 04:02:28,Monday,Fall,Evening,Low,5,1,38,38,40,125,203,Discharged,1
3,HOSP-2-20240227-0001,PAT-00004,HOSP-2,Riverside Medical Center,Urban,2024-02-27 00:31:13,Tuesday,Winter,Evening,High,4,5,94,8,16,64,88,Discharged,2
4,HOSP-1-20240306-0002,PAT-00005,HOSP-1,Springfield General Hospital,Urban,2024-03-06 16:52:26,Wednesday,Spring,Afternoon,Low,4,8,74,26,29,63,118,Discharged,1

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 19 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Visit ID                            5000 non-null   str
 1   Patient ID                          5000 non-null   str
 2   Hospital ID                         5000 non-null   str
 3   Hospital Name                       5000 non-null   str
 4   Region                              5000 non-null   str
 5   Visit Date                          5000 non-null   str
 6   Day of Week                         5000 non-null   str
 7   Season                              5000 non-null   str
 8   Time of Day                         5000 non-null   str
 9   Urgency Level                       5000 non-null   str
 10  Nurse-to-Patient Ratio              5000 non-null   int64
 11  Specialist Availability             5000 non-null   int64
 12  Facility Size (Beds)                5000 non-null   int64
 13  Time to Registration (min)          5000 non-null   int64
 14  Time to Triage (min)                5000 non-null   int64
 15  Time to Medical Professional (min)  5000 non-null   int64
 16  Total Wait Time (min)               5000 non-null   int64
 17  Patient Outcome                     5000 non-null   str
 18  Patient Satisfaction                5000 non-null   int64
dtypes: int64(8), str(11)
memory usage: 742.3 KB

The data set contain 5000 ROws and 19 COlumns.8 columns are Integers and 11 are str.

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    3.3 Initial Data Inspection
</h3>

In [24]:
df.isnull().sum().sort_values(ascending=False)

Visit ID                              0
Patient ID                            0
Hospital ID                           0
Hospital Name                         0
Region                                0
Visit Date                            0
Day of Week                           0
Season                                0
Time of Day                           0
Urgency Level                         0
Nurse-to-Patient Ratio                0
Specialist Availability               0
Facility Size (Beds)                  0
Time to Registration (min)            0
Time to Triage (min)                  0
Time to Medical Professional (min)    0
Total Wait Time (min)                 0
Patient Outcome                       0
Patient Satisfaction                  0
dtype: int64

The Data is Contain no NUll values or Mising Values.

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    3.5 Removing Duplicate Records
</h3>

In [25]:
df.duplicated().sum()

np.int64(0)

So the data set contain no Duplicate values

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    3.6 Date & Time Conversion
</h3>

In [26]:
df.columns

Index(['Visit ID', 'Patient ID', 'Hospital ID', 'Hospital Name', 'Region',
       'Visit Date', 'Day of Week', 'Season', 'Time of Day', 'Urgency Level',
       'Nurse-to-Patient Ratio', 'Specialist Availability',
       'Facility Size (Beds)', 'Time to Registration (min)',
       'Time to Triage (min)', 'Time to Medical Professional (min)',
       'Total Wait Time (min)', 'Patient Outcome', 'Patient Satisfaction'],
      dtype='str')

In [27]:
df['Visit Date']=pd.to_datetime(df['Visit Date'])

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 19 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Visit ID                            5000 non-null   str
 1   Patient ID                          5000 non-null   str
 2   Hospital ID                         5000 non-null   str
 3   Hospital Name                       5000 non-null   str
 4   Region                              5000 non-null   str
 5   Visit Date                          5000 non-null   datetime64[us]
 6   Day of Week                         5000 non-null   str
 7   Season                              5000 non-null   str
 8   Time of Day                         5000 non-null   str
 9   Urgency Level                       5000 non-null   str
 10  Nurse-to-Patient Ratio              5000 non-null   int64
 11  Specialist Availability             5000 non-null   int64
 12  Facility Size (Beds)                5000 non-null   int64
 13  Time to Registration (min)          5000 non-null   int64
 14  Time to Triage (min)                5000 non-null   int64
 15  Time to Medical Professional (min)  5000 non-null   int64
 16  Total Wait Time (min)               5000 non-null   int64
 17  Patient Outcome                     5000 non-null   str
 18  Patient Satisfaction                5000 non-null   int64
dtypes: datetime64[us](1), int64(8), str(10)
memory usage: 742.3 KB

Successfully converted to date_time column

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    3.7 Creating Time-Based Feature
</h3>

In [35]:
df['DayOfWeek'] = df['Visit Date'].dt.day_name()       # Monday, Tuesday...
df['Month'] = df['Visit Date'].dt.month                # 1-12
df['Is_Weekend'] = df['DayOfWeek'].isin(['Saturday', 'Sunday']).astype(int)
df['hours']=df['Visit Date'].dt.hour

In [37]:
print(df.columns)
print("---------------------------------------------------------")
df.head()

Index(['Visit ID', 'Patient ID', 'Hospital ID', 'Hospital Name', 'Region',
       'Visit Date', 'Day of Week', 'Season', 'Time of Day', 'Urgency Level',
       'Nurse-to-Patient Ratio', 'Specialist Availability',
       'Facility Size (Beds)', 'Time to Registration (min)',
       'Time to Triage (min)', 'Time to Medical Professional (min)',
       'Total Wait Time (min)', 'Patient Outcome', 'Patient Satisfaction',
       'DayOfWeek', 'Month', 'Is_Weekend', 'hours'],
      dtype='str')
---------------------------------------------------------

,Visit ID,Patient ID,Hospital ID,Hospital Name,Region,Visit Date,Day of Week,Season,Time of Day,Urgency Level,...,Time to Registration (min),Time to Triage (min),Time to Medical Professional (min),Total Wait Time (min),Patient Outcome,Patient Satisfaction,DayOfWeek,Month,Is_Weekend,hours
0,HOSP-1-20240210-0001,PAT-00001,HOSP-1,Springfield General Hospital,Urban,2024-02-10 20:20:56,Saturday,Winter,Late Morning,Medium,...,17,22,66,105,Discharged,1,Saturday,2,1,20
1,HOSP-3-20241128-0001,PAT-00002,HOSP-3,Northside Community Hospital,Rural,2024-11-28 02:07:47,Thursday,Fall,Evening,Medium,...,9,30,30,69,Discharged,3,Thursday,11,0,2
2,HOSP-3-20240930-0002,PAT-00003,HOSP-3,Northside Community Hospital,Rural,2024-09-30 04:02:28,Monday,Fall,Evening,Low,...,38,40,125,203,Discharged,1,Monday,9,0,4
3,HOSP-2-20240227-0001,PAT-00004,HOSP-2,Riverside Medical Center,Urban,2024-02-27 00:31:13,Tuesday,Winter,Evening,High,...,8,16,64,88,Discharged,2,Tuesday,2,0,0
4,HOSP-1-20240306-0002,PAT-00005,HOSP-1,Springfield General Hospital,Urban,2024-03-06 16:52:26,Wednesday,Spring,Afternoon,Low,...,26,29,63,118,Discharged,1,Wednesday,3,0,16

<h3 style="color:#CC0000; 
           background-color:#CCFFE5; 
           padding:10px; 
           border-radius:8px;">
    3.8 Creating Age Groups
</h3>